#docker compose -f docker-compose-metrics-author.yml up -d
version: '3.3'
services:
  dbserver:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: distribuida
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "c:/db-distribuida:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    expose:
      - 5432
  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500
  proxy:
    image: traefik:v3.3.1
    command: |
      --api.insecure=true
      --providers.consulCatalog
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.refreshInterval=5s
      --providers.consulCatalog.endpoint.address=consul:8500
      --providers.docker
      --providers.docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "80:80"
    expose:
      - 80
    depends_on:
      - consul
  authors:
    image: reymon4/app_authors:latest
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.router-app-authors.rule=PathPrefix(`/app-authors-1`)"
        - "traefik.http.routers.router-app-authors.middlewares=middleware-app-authors-1"
        - "traefik.http.middlewares.middleware-app-authors-1.stripPrefix.prefixes=/app-authors-1"
    ports:
      - "7070:8080"
    expose:
      - 8080
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: root
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      QUARKUS_HIBERNATE-ORM_METRICS_ENABLED: true
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs:/etc/prometheus
    ports:
      - "9090:9090"
    expose:
        - 9090
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    expose:
      - 3000
  postgresql-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_URI: "dbserver:5432/distribuida?sslmode=disable"
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: root
    expose:
      - 9187