rootProject.name = "ejercicioClase"
include("ejemploCDI")
include("ejemploRest")
include("ejemploJPA")
include("ejemploQuarkus")
include("app_authors")
include("app_books")
include("app_authors_spring")
include("app_books_spring")
include("deployment")
