apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authors
  labels:
    app: app-authors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-authors
  template:
    metadata:
      name: app-authors
      labels:
        app: app-authors
    spec:
      containers:
        - name: app-authors
          image: docker.io/reymon4/app_authors:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://clases.postgres.database.azure.com:5432/distribuida
            - name: QUARKUS_DATASOURCE_USERNAME
              value: distribuida
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: root2025$
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
            - name: QUARKUS_HTTP_PORT
              value: "8080"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-authors-services
spec:
  type: ClusterIP
  selector:
    app: app-authors
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      